
DROP TABLE Manager CASCADE CONSTRAINTS;


DROP TABLE Clerk CASCADE CONSTRAINTS;


DROP TABLE Salaries CASCADE CONSTRAINTS;


DROP TABLE Worker CASCADE CONSTRAINTS;


DROP TABLE Departments CASCADE CONSTRAINTS;


DROP TABLE Branches CASCADE CONSTRAINTS;
